baseURL = 'https://mikkegt.github.io/hugo/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'SimpleIntro'

[params]
    mainbg = "https://picsum.photos/1920/1080"
    name = "John Doe"
    mainTitle = "Simple-intro"
    mainText = "Just simple intro theme for hugo"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "#skills"
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "#projects"
    [[menu.main]]
        identifier = "privacy"
        name = "Privacy"
        url = "#privacy"
    