baseURL = 'https://mikkegt.github.io/hugo/'
languageCode = 'en-us'
title = 'elink'
theme = 'SimpleIntro'

[params]
    mainbg = "https://picsum.photos/1920/1080"
    name = "elink"
    mainTitle = "Hello, World"
    mainText = "Thank you for coming my website"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "#skills"
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "#projects"
    [[menu.footer]]
        identifier = "contact"
        name = "Contact"
        url = "https://forms.gle/JefKx45aXnHjDNj36"
    [[menu.footer]]
        identifier = "privacy"
        name = "Privacy"
        url = "/privacy/"
    